### ISSUE TITLE
distorted webcam view in portrait mode

### ISSUE THREAD

**Issue by gour** [mynaparrot/plugNmeet-client#18] opened 2022-04-06 06:30 UTC
Hello,

I'm evaluating whether plugNmeet can replace our need for BBB...several of our members are accessing our non-profit meetings by using their smart phones and I noticed that, in comparison with BBB which render their webcam view properly in e.g. portrait view, with plugNmeet it distorts the view by expanding it horizontally to "fill" the camera's border view which is quite annoying?

I'd gladly try it tomorrow during our regular meeting, but it's a show stopper. :-(

Sincerely,
Gour

**Comment by jibon57** [comment] 2022-04-06 06:46
@gour is it possible you to send some screenshots? Also I've transferred this to client repo.

**Comment by gour** [comment] 2022-04-06 08:12
> @gour is it possible you to send some screenshots? Also I've transferred this to client repo.

Submitted to your ticket system.

**Comment by wbobteng** [comment] 2022-04-06 09:02
![bbb-webcam](https://user-images.githubusercontent.com/34347796/161937862-1882e34a-4706-4cba-935c-5ad58afa18fb.png)
This is from BBB 
![pnmeet-distorsion](https://user-images.githubusercontent.com/34347796/161937968-16b76ced-859d-4d24-bcaa-9928636cacf6.png)
This is from plugNmeet 

@gour try to keep one channel to communicate is more efficient. Thanks

**Comment by Abdulkader69** [comment] 2022-04-06 09:38
hey @gour,
Did you use any virtual background for mobile view?

**Comment by gour** [comment] 2022-04-06 09:51
> hey @gour, Did you use any virtual background for mobile view?

Nope and I know that people who  tried plugNmeet on our meeting where I was moderator didn't use them either.

**Comment by wbobteng** [comment] 2022-04-06 10:25
@gour We are trying to reproduce the problem, can you guide us a little bit more.
What kind of mobile devices are you using? Android or iPhone, in which browser? 
Are the mobile devices joined as attendees or moderators?
Is the camera displayed normally in the beginning when you enter the room? 
By doing what you get this problem? something thing like changing the layout of the phone from vertical to the horizon? or from horizon to vertical? 

Thanks for your kindly help to debug this issue.

**Comment by gour** [comment] 2022-04-06 11:26
>  What kind of mobile devices are you using? Android or iPhone, in which browser? 

Android.

> Are the mobile devices joined as attendees or moderators? 

attendees

> Is the camera displayed normally in the beginning when you enter the room? 

It is displayed normally when in webcam-selection dialog, but as soon one enters into plugNmeet it is distorted.

> By doing what you get this problem? something thing like changing the layout of the phone from vertical to the horizon? or from horizon to vertical?

It seems that it does not matter...moreover, the screenshot which I attached is from the moderator's desktop screen, iow. the problem is not just on phone/host view, but on the remote screen of other attendees who were wondering about distorted remote view.

> Thanks for your kindly help to debug this issue.

I'm glad I can be of any help improving plugNmeet seeing it as having great potential and *less* problematic deployment than with BBB. Lastly, I'd like to be able that we leave Zoom  in exchange for open-source solution. ;)

**Comment by wbobteng** [comment] 2022-04-06 11:43
@gour  Many thanks for your details information, 
If it is possible, help us do another test with another mobile phone. See if the problem still happening or not. 
Maybe the problem is related specifically to your mobile settings. 
We tried all of our mobiles(android) in our team, still can not reproduce this issue. 

Thanks

**Comment by jibon57** [comment] 2022-04-06 12:03
@gour I'll also recommend you to try from: https://demo.plugnmeet.com/login.html

**Comment by gour** [comment] 2022-04-06 13:22
> If it is possible, help us do another test with another mobile phone. See if the problem still happening or not.

With our installation the problem does persist..tried even with other browser (Chrome).

So, I suggest you to try out our installation - Bob is still admin user there...

> Maybe the problem is related specifically to your mobile settings.

I don't think so.

> @gour I'll also recommend you to try from: https://demo.plugnmeet.com/login.html

At the Demo site, it seems that it does work with all our phones and with different browsers - Brave, Chrome & Firefox.

I bet it's different version of plugin and/or you have fixed something in the meantime?

I'd be curious if you can give some try on our own installation....


SIncerely

**Comment by wbobteng** [comment] 2022-04-06 13:32
@gour  Thanks for the testing. 
Can you update your client installation by clicking that update button at plugNmeet server settings?
![update](https://user-images.githubusercontent.com/34347796/161986262-5c804099-701c-45f1-8bb9-d808c059b9a4.png)
Also, make sure the WordPress plugin is the latest version. 

After that can do another test. see if problem been solved or not 

Thanks

**Comment by gour** [comment] 2022-04-06 15:17
> @gour Thanks for the testing. Can you update your client installation by clicking that update button at plugNmeet server settings? 

Updated.

> Also, make sure the WordPress plugin is the latest version.

Plugin was also update to 1.0.3.

> After that can do another test. see if problem been solved or not

On our installation, the problem is still visible when the phone is in landscape mode, while in portrait mode it is now OK.

However, on the demo site, the both modes are rendered OK.

Sincerely,
Gour

**Comment by jibon57** [comment] 2022-04-10 01:47
@gour try latest client. Should be fixed.

**Closed by jibon57** 2022-04-10 01:47 UTC
